# Generated by Django 2.2.16 on 2023-01-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
    ]
